### PR TITLE
fix: https buffers should not be checked for a file

### LINKED ISSUE #166: 1.0.3: cannot pass buffer/string certificates to https option anymore
* Operating System: macOS 10.13.3
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.11.1
* webpack-serve Version: 1.0.3

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
import startDevServer from 'webpack-serve';
import { certificateFor } from 'devcert';

// https holds buffers
const https = await certificateFor('localhost', {
 skipHostsFile: true,
 skipCertuil: false,
});

startDevServer({
 // other config does not matter, reproducible either way
 https,
});

```

### Expected Behavior
Should start up the dev-server with a valid https cert.

### Actual Behavior
Throws an error:

`An error was thrown while starting webpack-serve.
   { Error: ENAMETOOLONG: name too long, lstat 'Certificate:
{...certificate data}
`

### How Do We Reproduce?

Generate a self-signed certificate using `devcert` and pass it in as `https` option to webpack-serve >= 1.0.3.

Before 1.0.3 it was perfectly fine to pass buffers/strings for each entry in the https options, but since 1.0.3 it does not work anymore.

I think this bug was introduced in https://github.com/webpack-contrib/webpack-serve/commit/e030696cf0c64c97582f33c1ae3492918c23fb41#diff-763aa8deb604d725a74f8304903c1422R78

It basically runs `fs.lstatSync()` on the actual passed string/buffer value of the cert/key, which of course is too long. We'll need to check first weather it's an actual file (path) before using lstat.

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #166. The fix to read from paths passed for https properties/flags didn't take into account the size of buffers and lstat's max filename length.

### Breaking Changes

None

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -4,9 +4,11 @@ const { register } = require('../lib/global');
...
-require('./tests/cli');
-require('./tests/events');
-require('./tests/log');
+process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
+
+// require('./tests/api');
+// require('./tests/bus');
+// require('./tests/cli');
+// require('./tests/events');
+// require('./tests/log');
```
Comment (ooflorent) [inline test/test.js]: Is this a mistake?
